### PR TITLE
Added live the dream after testing the link

### PR DESCRIPTION
**Pull request by JayneJacobs**

### CODE REVIEW

**Comment by JayneJacobs** [comment]
Please Merge?

**Comment by JayneJacobs** [comment]
Please Merge!

**Comment by JayneJacobs** [comment]
merge Please!

**Comment by morosebose** [comment]
@casey-collab

**Comment by JayneJacobs** [comment]
Please review this, @casey-collab

**Comment by JayneJacobs** [comment]
@casey-collab please review : 
removed blank file 
reduced line length

**Comment by casey-collab** [comment]
Looks great! :crown:

**Comment by JayneJacobs** [comment]
thank you!!!!

----- Original Message -----From: Casey Collaborator <notifications@github.com>To: udacity/create-your-own-adventure <create-your-own-adventure@noreply.github.com>Cc: JayneJacobs <jaynejacobs@comcast.net>Sent: Fri, 15 Jan 2016 04:14:25 -0000 (UTC)Subject: Re: [create-your-own-adventure] Added live the dream after testing the link (#3170)

Merged #3170.
&mdash;Reply to this email directly or view it on GitHub.

**Pull request merged**
