### PR TITLE
Chat with a hawkstrider.

### PR DESCRIPTION
**Pull request by LeeDarren**
Interactive chat with a hawkstrider

### CODE REVIEW

**Comment by LeeDarren** [comment]
Please review this, @casey-collab

**Comment by casey-collab** [comment]
Unfortunately, pull requests adding more than 100 lines are not eligible for automatic merging.  If you wish to have this pull request auto-merged, please update it to add 100 lines or fewer.

**Comment by LeeDarren** [comment]
When I push only earlier commits, the bot won't accept it because there are broken links which only work after later commits.  And if I push those later commits, then I am again over the 100 line limit.  I don't want to intentionally break my files with correct links to files that haven't been added yet and I can't add those files because I'll be over the 100 line limit.  Just going to leave this and hope someone may merge it one day.

**Comment by LeeDarren** [comment]
Trying this one more time.
Please review this, @casey-collab

**Comment by casey-collab** [comment]
Unfortunately, pull requests adding more than 100 lines are not eligible for automatic merging.  If you wish to have this pull request auto-merged, please update it to add 100 lines or fewer.

**Pull request closed without merging**
