### PR TITLE
Please review this, @casey-collab

### PR DESCRIPTION
**Pull request by spraveenit**
Please review this, @casey-collab

[Review on Reviewable](https://reviewable.io/reviews/udacity/create-your-own-adventure/2157)

### CODE REVIEW

**Comment by casey-collab** [comment]
It looks like the file `Tamil/Thirukural.md` is empty.  Please make sure you don't add empty files to the repository.  You could add one sentence to this file, or delete the option that leads to it.

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by spraveenit** [comment]
Please review this, @casey-collab

**Comment by casey-collab** [comment]
Looks great! :ice_cream:

**Pull request merged**
