### PR TITLE
Add a terrible pun to the bear story

### PR DESCRIPTION
**Pull request by desromj**
Please review this, @casey-collab

[Review on Reviewable](https://reviewable.io/reviews/udacity/create-your-own-adventure/2508)

### CODE REVIEW

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by desromj** [comment]
GitHub is saying the branch is up-to-date and can be automatically merged. I don't seem able to merge  or fast-forward merge master into my local branch, as it says "Everything is up-to-date". Is there something I'm missing?

**Comment by cbuckey-uda** [comment]
Yeah, I don't see the conflict either. Sorry about that! @casey-collab, can you check again?

**Comment by casey-collab** [comment]
Looks great! :checkered_flag:

**Comment by desromj** [comment]
Thanks, @cbuckey-uda, for the help and the course! How have I been getting by with my coding without Git or GitHub until now? It's so powerful!

**Comment by cbuckey-uda** [comment]
You're welcome! Glad you enjoyed the course. :smile:

**Pull request merged**
