### PR TITLE
several comments added by Anya

### PR DESCRIPTION
**Pull request by agerasimchuk**
several easy comments

[Review on Reviewable](https://reviewable.io/reviews/udacity/create-your-own-adventure/1834)

### CODE REVIEW

**Comment by cbuckey-uda** [comment]
@casey-collab, please review this

**Comment by casey-collab** [comment]
Changes to the README cannot be automatically merged. Feel free to make a change to the story instead!

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by cbuckey-uda** [comment]
Closing this pull request due to lack of activity. If you ever have time to respond to the comments above, feel free to re-open it.

**Pull request closed without merging**
