### PR TITLE
Lighter flavor text in dig_down.md

### PR DESCRIPTION
**Pull request by mcvicker**
@casey-collab please add my lighter flavor text

### CODE REVIEW

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by mcvicker** [comment]
@casey-collab can't find any merge conflicts

**Comment by casey-collab** [comment]
Looks great! :dog:

**Pull request merged**
