### PR TITLE
Change McGyver jumping off cliff, giving more detail

### PR DESCRIPTION
**Pull request by biffster**
Change McGyver jumping off cliff, giving more detail

### CODE REVIEW

**Comment by cbuckey-uda** [comment]
@casey-collab, please review this

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by biffster** [comment]
I have addressed the conflicts, it's good by me!

**Comment by cbuckey-uda** [comment]
@casey-collab, please take another look

**Comment by casey-collab** [comment]
Looks great! :crown:

**Pull request merged**
