### PR TITLE
explain more yoga benefits(updated)

### PR DESCRIPTION
**Pull request by TheObtuseAutodidact**
Please review this, @casey-collab

### CODE REVIEW

**Comment by TheObtuseAutodidact** [comment]
Please review this, @casey-collab

**Comment by casey-collab** [comment]
It looks like the files `english/yoga/.DS_Store`, `.DS_Store`, and`english/.DS_Store` are empty.  Please make sure you don't add empty files to the repository.  You could add one sentence to each file, or delete the options that lead to them.

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by TheObtuseAutodidact** [comment]
updated,  @casey-collab

**Comment by casey-collab** [comment]
Looks great! :purple_heart:

**Pull request merged**
