### PR TITLE
Mycontribution

### PR DESCRIPTION
**Pull request by muratgenctav**

### CODE REVIEW

**Comment by muratgenctav** [comment]
Please review this, @casey-collab

**Comment by casey-collab** [comment]
It looks like the file `turkce/catalla-kaz/metali-cek/cakmakla-ilerle/hatmiyle-yuzles/goksel/goksel.md` is empty.  Please make sure you don't add empty files to the repository.  You could add one sentence to this file, or delete the option that leads to it.

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by muratgenctav** [comment]
Please review this, @casey-collab

**Comment by casey-collab** [comment]
Looks great! :wind_chime:

**Pull request merged**
