### PR TITLE
Update Stargate

### PR DESCRIPTION
**Pull request by mangowolf**
Please review this, @casey-collab

### CODE REVIEW

**Comment by casey-collab** [comment]
It looks like this pull request deletes quite a few lines. Was this a mistake?

**Comment by mangowolf** [comment]
Yes, i'm not quite sure how that happened, maybe i will just start over.

**Comment by mangowolf** [comment]
Please review this, @casey-collab, I think i have fixed it so it does not delete all those other lines.

**Comment by casey-collab** [comment]
It looks like this pull request deletes quite a few lines. Was this a mistake?

**Pull request closed without merging**
