### PR TITLE
added jump story

### PR DESCRIPTION
**Pull request by feltonjsd**
Please review @casey-collab

### CODE REVIEW

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by feltonjsd** [comment]
fixed merge conflicts @casey-collab

**Comment by casey-collab** [comment]
Unfortunately this pull request could not be automatically reviewed due to technical difficulty.

**Comment by feltonjsd** [comment]
technical difficulty? I will try again! @casey-collab

**Comment by casey-collab** [comment]
Unfortunately this pull request could not be automatically reviewed due to technical difficulty.

**Pull request closed without merging**
