### PR TITLE
Replace all occurances of '] (' with ']('

### PR DESCRIPTION
**Pull request by third774**
Was tired of seeing links broken by the same mistake throughout
the project, so I used Sublime to find and replace all occurances
of '] (' with '](' to clean things up.

@casey-collab - Please review!

[Review on Reviewable](https://reviewable.io/reviews/udacity/create-your-own-adventure/1916)

### CODE REVIEW

**Comment by casey-collab** [comment]
It looks like this pull request deletes quite a few lines. Was this a mistake?

**Comment by third774** [comment]
Nope! Have a look and you'll see 134 broken links fixed. :D

**Comment by cbuckey-uda** [comment]
Well, the links weren't actually broken. GitHub displays links properly even if they have a space. I agree it's better to have a consistent style, though.

**Comment by third774** [comment]
Aha - they must have just appeared as broken when I was viewing the .md files locally using a Chrome extension. Thanks for the course! Love it!

**Comment by cbuckey-uda** [comment]
Glad you enjoyed the course! And yeah, there's many different "flavors" of markdown. GitHub uses "GitHub Flavored Markdown" (that is, their own specialized version), so it's not surprising that a different markdown viewer would not accept these links.

**Pull request merged**
