### PR TITLE
Add link out of call-scotty to experience

### PR DESCRIPTION
**Pull request by ntb001**
call-scotty was a dead end. This will keep the story going. Please review this, @casey-collab

### CODE REVIEW

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by ntb001** [comment]
try again @casey-collab ?

**Comment by casey-collab** [comment]
Looks great! :dog:

**Pull request merged**
