### PR TITLE
Add 2 sentences to marshmallow story to make it more interesting

### PR DESCRIPTION
**Pull request by itoroAtt**
Please review this, @casey-collab

### CODE REVIEW

**Comment by cbuckey-uda** [comment]
@casey-collab, you there?

**Comment by casey-collab** [comment]
Looks great! :smile:

**Comment by itoroAtt** [comment]
Yes I am ☺

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Pull request merged**
