### PR TITLE
Add Gran Hermano in espanol

### PR DESCRIPTION
**Pull request by christophavila**
Add Gran Hermano in espanol with a new pull request

### CODE REVIEW

**Comment by christophavila** [comment]
Conflicts have been solved, could you please help me to add my part?.

Thanks!

**Comment by christophavila** [comment]
Any news? :(

**Comment by pmallory** [comment]
@casey-collab Can you review this PR please?

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by christophavila** [comment]
I´m facing some issues, I have done the folowing:
>_(add-granhermano) espanol $ git pull https://github.com/udacity/create-your-own-adventure.git _master
> fix the problems in espanol/canudos.md
>_(add-granhermano) espanol $ git add canudos.md_
>_(add-granhermano) espanol $ git commit_
>_(add-granhermano) espanol $ git push origin add-granhermano _
To https://github.com/christophavila/create-your-own-adventure.git
 ! [rejected]        add-granhermano -> add-granhermano (fetch first)
error: failed to push some refs to 'https://github.com/christophavila/create-your-own-adventure.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

What should I do now?

Thanks!

**Comment by christophavila** [comment]
Sorry guys but now Im very confused, the branch "add-granhermano" in my fork shows this message:

"This branch is 2 commits ahead, 52 commits behind udacity:master."

I ´ve been searching for some answers in stackoverflow but none of the answers works for me now... :(

**Comment by christophavila** [comment]
Any news? I don´t want to close another pull request again. I would rally like to fix this one and understand how to solve this issue.

Thanks in advance!

**Pull request closed without merging**
