### PR TITLE
Add a brukselka in a pocket story.

### PR DESCRIPTION
**Pull request by gmb55**

### CODE REVIEW

**Comment by gmb55** [comment]
@casey-collab

**Comment by casey-collab** [comment]
Hey! Me! Review this @casey-collab

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Pull request closed without merging**
