### PR TITLE
Added Hebrew to the adventure

### PR DESCRIPTION
**Pull request by dangalg**
Hope it works this time...:)

### CODE REVIEW

**Comment by cbuckey-uda** [comment]
@casey-collab, please review this

**Comment by casey-collab** [comment]
Unfortunately this pull request could not be automatically reviewed due to technical difficulty.

**Comment by cbuckey-uda** [comment]
Looks good, thanks! :peach:

**Comment by dangalg** [comment]
Yay! Thank you.

**Comment by cbuckey-uda** [comment]
You're welcome!

**Pull request merged**
