### PR TITLE
Feat: Add new lines on this page

### PR DESCRIPTION
**Pull request by Hcskul**
Adding to a german page with a great white shark.

@casey-collab

Please review this, @casey-collab

### CODE REVIEW

**Comment by Hcskul** [comment]
@casey-collab

Please review this, @casey-collab

**Comment by casey-collab** [comment]
Hey! Me! Review this @casey-collab

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by casey-collab** [comment]
Hey me! Review this @casey-collab

**Comment by casey-collab** [comment]
Looks great! :rabbit:

**Pull request merged**
