### PR TITLE
Merged with local master

### PR DESCRIPTION
**Pull request by moglucy**
@casey-collab I think I have done what you requested. Thanks for the help to date.

### CODE REVIEW

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by moglucy** [comment]
@casey-collab few! I hope this is it. It finally says it can merge. Steep learning curve. Thanks.

**Comment by casey-collab** [comment]
Looks great! :wind_chime:

**Pull request merged**
