### PR TITLE
Add Casey won't accept fix typo in Chinese folder

### PR DESCRIPTION
**Pull request by xuxyang**
Please review this, @casey-collab

### CODE REVIEW

**Comment by casey-collab** [comment]
Looks great! :octocat:

**Comment by casey-collab** [comment]
Unfortunately this pull request could not be automatically reviewed due to technical difficulty.

**Comment by xuxyang** [comment]
The last 2 commits are for me to practice merging conflict in pull request. Please review again, @casey-collab

**Comment by casey-collab** [comment]
Looks great! :octocat:

**Pull request merged**
