### PR TITLE
The king in yellow!

### PR DESCRIPTION
**Pull request by jmckeever79**
[Review on Reviewable](https://reviewable.io/reviews/udacity/create-your-own-adventure/2185)

### CODE REVIEW

**Comment by cbuckey-uda** [comment]
@casey-collab, please review this

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by cbuckey-uda** [comment]
Hm, it looks like this pull request is a duplicate of https://github.com/udacity/create-your-own-adventure/pull/2155, so I'm going to close it. If I've misunderstood, please let me know.

**Comment by cbuckey-uda** [comment]
Sorry about the confusing comments. It looks like this pull request has the same changes as https://github.com/udacity/create-your-own-adventure/pull/2155, which has already been merged. That means this one has actually been merged as well, in the sense that its changes are already merged. Casey got confused and thought there was a conflict, but actually no action is needed.

**Pull request merged**
