### PR TITLE
Add new storyline in malayalam

### PR DESCRIPTION
**Pull request by remenraj**

### CODE REVIEW

**Comment by krishmishra** [comment]
Please review this, @casey-collab

**Comment by KhyatiGanatra** [comment]
Added lines to Gujararti

**Comment by vta92** [comment]
please review

**Comment by ohmslawct** [comment]
@casey-collab please merge

**Comment by whjdchnn** [comment]
Please review this, @casey-collab

**Comment by brosefzai** [comment]
Please review this, @casey-collab

**Pull request closed without merging**
