### PR TITLE
Add a sentence, the story the Choking Doberman, to marshmallow.md

### PR DESCRIPTION
**Pull request by msprj2010**
Add dog_finger folder and dog_finger.md file in english folder

### CODE REVIEW

**Comment by msprj2010** [comment]
Please take a look. Thx :)

**Comment by msprj2010** [comment]
Please take a look. Thx :)

**Comment by msprj2010** [comment]
Please review this, @casey-collab

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by msprj2010** [comment]
Please review this, @casey-collab

**Comment by casey-collab** [comment]
Looks great! :hibiscus:

**Pull request merged**
