### PR TITLE
"commit for pull request"

### PR DESCRIPTION
**Pull request by nimish1125**
pull request on new branch

[Review on Reviewable](https://reviewable.io/reviews/udacity/create-your-own-adventure/2788)

### CODE REVIEW

**Comment by cbuckey-uda** [comment]
@casey-collab, please review this

**Comment by casey-collab** [comment]
Changes to the README cannot be automatically merged. Feel free to make a change to the story instead!

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by cbuckey-uda** [comment]
This looks like a test pull request, which is fine, but I only want to merge contributions to the story so I'm going to close it. If I've misunderstood, please re-open the pull request and let me know.

**Pull request closed without merging**
