### PR TITLE
English Addition - smoke, eat, and escape adventure

### PR DESCRIPTION
**Pull request by nyguerrillagirl**
This is to satisfy the requirement for the Git and GitHub course.

### CODE REVIEW

**Comment by cbuckey-uda** [comment]
@casey-collab, please review this

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Can you resolve the merge conflicts locally and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by cbuckey-uda** [comment]
Closing this pull request due to lack of activity. If you ever have time to resolve the merge conflicts, feel free to re-open it.

**Pull request closed without merging**
