### PR TITLE
Add option to do yoga

### PR DESCRIPTION
**Pull request by tofuninjah**
@casey-collab, please merge this.

### CODE REVIEW

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by cbuckey-uda** [comment]
@casey-collab, I don't see the merge conflict. Could you check again?

**Comment by casey-collab** [comment]
Looks great! :sunglasses:

**Pull request merged**
