### PR TITLE
updated

### PR DESCRIPTION
**Pull request by julianfrank**
All mine

[Review on Reviewable](https://reviewable.io/reviews/udacity/create-your-own-adventure/2055)

### CODE REVIEW

**Comment by cbuckey-uda** [comment]
@casey-collab, please review this

**Comment by casey-collab** [comment]
Changes to the README cannot be automatically merged. Feel free to make a change to the story instead!

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by cbuckey-uda** [comment]
This looks like a test pull request to me. That's fine, but I only want to merge continuations of the story, so I'm going to close it. If I've misunderstood, please let me know.

**Pull request closed without merging**
