### PR TITLE
Add change in ontvoering

### PR DESCRIPTION
**Pull request by willgates**
[Review on Reviewable](https://reviewable.io/reviews/udacity/create-your-own-adventure/1679)

### CODE REVIEW

**Comment by cbuckey-uda** [comment]
@casey-collab, please review this

**Comment by casey-collab** [comment]
Unfortunately this pull request could not be automatically reviewed due to technical difficulty.

**Comment by cbuckey-uda** [comment]
@willgates, I don't speak Dutch, but this looks like a significant change to me. I don't usually merge changes to existing parts of the story, unless they are fixing typos or other mistakes. Does this change fix a mistake? If so, I will be happy to merge it, but otherwise I suggest you think of a continuation to the story instead of changing what is already there.

**Comment by willgates** [comment]
Hi @cbuckey-uda, thanks for your comment. I'll make another contribution and close this request.

**Comment by cbuckey-uda** [comment]
Thanks! I look forward to seeing your change!

**Pull request closed without merging**
