### PR TITLE
change super hero to a woman

### PR DESCRIPTION
**Pull request by DeborahSchwartz**

### CODE REVIEW

**Comment by cbuckey-uda** [comment]
I'd be okay with making it gender neutral (superperson, superhero, or something), but changing the gender from the original author's intent seems a little sad to me. Or you could add something about a female hero or character somewhere else in the story.

**Comment by DeborahSchwartz** [comment]
Caroline,

 

Thanks for doing such a great job on this course. I tried to learn Git and GitHub on my own and got a bit lost. I thought your course design, questions, and examples were really helpful.

 

I got a bit lost in the section on pull requests – you clicked so fast through the GitHub part, but I kept watching and watching and finally got it.

 

In fact, I was doing a different course today and I made the sample project a Git project so I could keep track of all the versions easily. 

 

Many thanks to you and Sarah for working so hard on this course.

 

Deborah

 

PS: I get what you said about gender … but, as a long time vegan, I “veganized” all your recipes and by the time I got to this story, I thought maybe I should show my feminist tendencies as well. I’m not too happy about lack of compassion towards any sentient beings.

**Comment by cbuckey-uda** [comment]
@DeborahSchwartz, I'm glad you enjoyed the course! And I'm sorry the pull request section moved a bit fast for you. And I think it's great you created vegan versions of all the recipes!

**Comment by cbuckey-uda** [comment]
I'm going to close this pull request for the reason I mentioned above. If you'd like to make another pull request, or re-open and update this one based on my comment, please go ahead!

**Pull request closed without merging**
