### PR TITLE
Add changes to Chinese/大话西游.md at the end

### PR DESCRIPTION
**Pull request by cloudybw**
Check it out @casey-collab

### CODE REVIEW

**Comment by casey-collab** [comment]
Looks great! :melon:

**Comment by cloudybw** [comment]
@casey-collab

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Pull request merged**
