### PR TITLE
Fixed dead end in the shoulder check scenario to continue on to the t…

### PR DESCRIPTION
**Pull request by xalerons**
Fixed dead end in the shoulder check scenario to continue on to the tower. 
Please review this, @casey-collab

### CODE REVIEW

**Comment by morosebose** [comment]
@casey-collab

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by xalerons** [comment]
@casey-collab

**Comment by casey-collab** [comment]
Looks great! :sunglasses:

**Pull request merged**
