### PR TITLE
Add custom message to story

### PR DESCRIPTION
**Pull request by nikhiljuturu**
[Review on Reviewable](https://reviewable.io/reviews/udacity/create-your-own-adventure/2136)

### CODE REVIEW

**Comment by cbuckey-uda** [comment]
@casey-collab, please review this

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by nikhiljuturu** [comment]
Merge Conflicts have been resolved. Please let me know if anything else is needed

**Comment by cbuckey-uda** [comment]
@nikhiljuturu I'm not sure what went wrong, but I still see merge conflicts. Did you update the master branch of your fork to the state of the original repository before merging? If so, it could be that someone added another conflicting change in the mean time and you'll need to merge again.

**Comment by nikhiljuturu** [comment]
I have pulled upstream master again to my local master, merged it with my branch(spinoff) where my addition was added, pushed my spinoff branch to my github spinoff branch, and submitted a pull request to udacity/create-your-own-adventure. 

My github account's forked master branch (nikhiljuturu/create-your-own-adventure/tree/master) is the same as the day I've forked it.

**Comment by nikhiljuturu** [comment]
greencommit

**Comment by cbuckey-uda** [comment]
@nikhiljuturu, that's very curious, the merge conflicts are not showing up for me anymore. I'm not sure what changed. (Your process also sounds like it should work.)

@casey-collab, please take another look

**Comment by casey-collab** [comment]
Looks great! :hibiscus:

**Comment by nikhiljuturu** [comment]
Thank you all.

**Pull request merged**
