### PR TITLE
Committing my changes - Sithi

### PR DESCRIPTION
**Pull request by Vaseela**
Added a new file named 'vaporization' and linked it to liquid file.

### CODE REVIEW

**Comment by Vaseela** [comment]
Hi ,
Kindly review my changes and merge them @casey-collab.
Thanks!

**Comment by Vaseela** [comment]
Made some modifications as an extra file got created and a line was modified by mistake. I have corrected them and pushed the changes to my branch. Kindly review @casey-collab and approve the auto-merge.

**Comment by pmallory** [comment]
@casey-collab Can you take a look at this PR?

**Comment by casey-collab** [comment]
Looks great! :dog:

**Pull request merged**
