### PR TITLE
Rename directories.

### PR DESCRIPTION
**Pull request by cimere**
@casey-collab, please merge this.

### CODE REVIEW

**Comment by casey-collab** [comment]
Unfortunately this pull request could not be automatically reviewed due to technical difficulty.

**Comment by cbuckey-uda** [comment]
Hm, not sure what the trouble was. @casey-collab, please try again?

**Comment by casey-collab** [comment]
Unfortunately this pull request could not be automatically reviewed due to technical difficulty.

**Comment by cbuckey-uda** [comment]
This pull request looks like it probably causes problems because I'm guessing there are links throughout the repository that refer to the old directory names. If you want to rename them, you'd need to update all the links also.

**Comment by cbuckey-uda** [comment]
Closing this pull request due to lack of activity. If you ever have time to respond to the comment above, feel free to re-open it.

**Pull request closed without merging**
