### PR TITLE
Add line to story

### PR DESCRIPTION
**Pull request by langhimebaugh**
Please review this, @casey-collab

### CODE REVIEW

**Comment by langhimebaugh** [comment]
Please review this, @casey-collab

**Comment by casey-collab** [comment]
Looks great! :hibiscus:

**Comment by casey-collab** [comment]
Unfortunately this pull request could not be automatically reviewed due to technical difficulty.

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by pmallory** [comment]
huh, casey seems confused. This looks good to me!

**Pull request merged**
