### PR TITLE
Please review Thai beach #2 , @casey-collab

### PR DESCRIPTION
**Pull request by apiwatja**
[Review on Reviewable](https://reviewable.io/reviews/udacity/create-your-own-adventure/1714)

### CODE REVIEW

**Comment by cbuckey-uda** [comment]
@casey-collab, please review this

**Comment by casey-collab** [comment]
Unfortunately this pull request could not be automatically reviewed due to technical difficulty.

**Comment by cbuckey-uda** [comment]
It looks to me like these changes are not reachable from the rest of the repository. That is, a reader who starts at `language.md` and keeps clicking links will never reach these pages. Could you add an option that leads here into the existing story?

**Comment by cbuckey-uda** [comment]
Closing this pull request due to lack of activity. If you ever have time to respond to the comments above, feel free to re-open it.

**Pull request closed without merging**
