### PR TITLE
add line to weed

### PR DESCRIPTION
**Pull request by Johnedward**
@casey-collab

[Review on Reviewable](https://reviewable.io/reviews/udacity/create-your-own-adventure/2293)

### CODE REVIEW

**Comment by casey-collab** [comment]
It looks like this pull request deletes quite a few lines. Was this a mistake?

**Comment by Johnedward** [comment]
Oh no! I must have made a mistake I'll go try to to it again.

**Comment by cbuckey-uda** [comment]
@Johnedward, this looks like a huge change - GitHub shows 496 files have changed! I took a quick look, and it looks like a lot of the changes are fixing up whitespace, and you've also added quite a few new files. Is this accurate, or did something go wrong Git-wise?

The purpose of the repository is to make a story where each person has contributed only a small amount, so I would prefer a pull request that only adds one or a few files.

**Comment by Johnedward** [comment]
Hi Caroline

I think something went wrong john wise:-) I responded to someone yesterday
letting them Know it was a mistake. I have not been on since then though.
Do I need to remove my pull request?

**Comment by cbuckey-uda** [comment]
@Johnedward, I think I figured out the problem. This pull request says you want to merge these commits into "fix-dir-structure" from "master", but it should say you want to some commits into "master" from whatever you branch is (that is, the direction is backwards). I think the best thing to do will be delete this pull request, then make a new one that goes in the other direction.

**Comment by Johnedward** [comment]
Thanks I've gone ahead and canceled the pull request and will try again
later.

**Pull request closed without merging**
