### PR TITLE
docs: Add scenario with Mrs. Lancaster's father

### PR DESCRIPTION
**Pull request by shersom**
As an extra detail, this commit is meant to create a conflict in the
memories file to be able to try out the last part of the Udacity lesson.

@casey-collab, any problems?

### CODE REVIEW

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by shersom** [comment]
@casey-collab
Done!

**Comment by casey-collab** [comment]
Looks great! :fire:

**Pull request merged**
