### PR TITLE
Add link to chess and bear-story from dimension

### PR DESCRIPTION
**Pull request by sycarion**
Please review this, @casey-collab

### CODE REVIEW

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by sycarion** [comment]
Please review this, @casey-collab I believe that I have fixed the conflict.

**Comment by casey-collab** [comment]
Looks great! :fire:

**Pull request merged**
