### PR TITLE
Add sentence to ruderboot.md

### PR DESCRIPTION
**Pull request by jocwulf**
"Please review this, @casey-collab"

### CODE REVIEW

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by 13rac1** [comment]
:thinking: Why do you do this @casey-collab ? Check again!

**Comment by casey-collab** [comment]
Looks great! :octocat:

**Comment by 13rac1** [comment]
Seems like Github is taking much longer than expected to confirm "mergeability"

**Pull request merged**
