### PR TITLE
Contribute to story in espanol/canudos.md and created ...espanol/cuco/cuco.md

### PR DESCRIPTION
**Pull request by Fratley**

### CODE REVIEW

**Comment by morosebose** [comment]
@casey-collab

**Comment by Fratley** [comment]
Um, is there something I need to do?

**Comment by casey-collab** [comment]
Looks great! :star:

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by Fratley** [comment]
Thanks for letting me be a part of the story! Great tutorials, I expect to
use GitHub on my next big project, keep up the good work!

On Thu, Jan 7, 2016 at 4:02 PM, Casey Collaborator <notifications@github.com

**Pull request merged**
