### PR TITLE
My changes

### PR DESCRIPTION
**Pull request by jailorboy**
Added a storyline where the character goes to Nepal.

### CODE REVIEW

**Comment by jailorboy** [comment]
Please review this, @casey-collab

**Comment by casey-collab** [comment]
Unfortunately, pull requests adding more than 100 lines are not eligible for automatic merging.  If you wish to have this pull request auto-merged, please update it to add 100 lines or fewer.

**Comment by cbuckey-uda** [comment]
It looks like maybe you have accidentally committed a bunch of files ending with `~`. (I am guessing your editor created them.) Could you remove those? I believe they are what is making the pull request so long.

**Comment by cbuckey-uda** [comment]
Closing this pull request due to lack of activity. If you ever have time to respond to the comments above, feel free to re-open it.

**Comment by jailorboy** [comment]
Yeah, looks like my editor created those files. I committed the entire folder at once because I was too lazy to add the individual files and that's what caused all the problems.

**Pull request closed without merging**
