### PR TITLE
Add a new part of the story to a page and Juanito Nieves option

### PR DESCRIPTION
**Pull request by kiara-ottogalli**
I modified espanol/torre/estrategia/estrategia.md page and added a new option espanol/torre/estrategia/juanito/juanito.md

Modifiqué la página espanol/torre/estrategia/estrategia.md y añadí una nueva opción espanol/torre/estrategia/juanito/juanito.md

### CODE REVIEW

**Comment by kiara-ottogalli** [comment]
I think it's worth merging @casey-collab

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by kiara-ottogalli** [comment]
Ready to merge! @casey-collab

**Comment by casey-collab** [comment]
Looks great! :sunny:

**Pull request merged**
