### PR TITLE
add yoruba language

### PR DESCRIPTION
**Pull request by mayoreee**

### CODE REVIEW

**Comment by mayowaegbinola** [comment]
Please review this, @casey-collab.

**Comment by mayowaegbinola** [comment]
@casey-collab, help me merge this. Thanks!

**Comment by casey-collab** [comment]
Hey! Me! Review this @casey-collab

If it cannot be merged just mention me and I'll check it again.

**Comment by casey-collab** [comment]
It looks like this pull request deletes quite a few lines. Was this a mistake?

**Pull request closed without merging**
