### PR TITLE
Add mystory to the storyline of create-your-own-adventure

### PR DESCRIPTION
**Pull request by codergs**
[Review on Reviewable](https://reviewable.io/reviews/udacity/create-your-own-adventure/2677)

### CODE REVIEW

**Comment by codergs** [comment]
Please review this, @casey-collab

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by cbuckey-uda** [comment]
@casey-collab, I don't see the conflict. Could you check again?

**Comment by casey-collab** [comment]
Looks great! :palm_tree:

**Comment by codergs** [comment]
It seems the merge went through. Let me know if I need to do anything. Thanks Guys!

**Pull request merged**
