### PR TITLE
added macguyver content

### PR DESCRIPTION
**Pull request by tromboneamafone**
please review @casey-collab

### CODE REVIEW

**Comment by tromboneamafone** [comment]
I reduced the line to less than 120 characters. Im not sure if i need to try for a re-pull? or does the change auto go through?

**Comment by cbuckey-uda** [comment]
@tromboneamafone, the change is automatically included in the current pull request. @casey-collab, please take another look.

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Can you resolve the merge conflicts locally and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by tromboneamafone** [comment]
please review @casey-collab

**Comment by casey-collab** [comment]
Looks great! :lollipop:

**Pull request merged**
