### PR TITLE
Play gta story

### PR DESCRIPTION
**Pull request by dgeniusudesign**
Changed story.

[Review on Reviewable](https://reviewable.io/reviews/udacity/create-your-own-adventure/1924)

### CODE REVIEW

**Comment by cbuckey-uda** [comment]
@casey-collab, please review this

**Comment by cbuckey-uda** [comment]
@casey-collab, you there?

**Comment by casey-collab** [comment]
Unfortunately this pull request could not be automatically reviewed due to technical difficulty.

**Comment by cbuckey-uda** [comment]
Looks good to me! :moneybag:

**Pull request merged**
