### PR TITLE
Instagram

### PR DESCRIPTION
**Pull request by dias94**
Added Instagram option to russian folder

### CODE REVIEW

**Comment by pmallory** [comment]
@casey-collab can you review this PR please?

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by dias94** [comment]
Ok , now you can try)

2016-03-26 0:29 GMT+06:00 Casey Collaborator <notifications@github.com>:

**Pull request merged**
