### PR TITLE
add solve-problem

### PR DESCRIPTION
**Pull request by zhuoweic**
Please review this, @casey-collab

### CODE REVIEW

**Comment by cbuckey-uda** [comment]
@casey-collab, please take another look

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Can you resolve the merge conflicts locally and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by cbuckey-uda** [comment]
Closing this pull request due to lack of activity. If you ever have time to resolve the merge conflicts, feel free to re-open it.

**Pull request closed without merging**
