### PR TITLE
Add a new episode yoyo

### PR DESCRIPTION
**Pull request by pobenliu**

### CODE REVIEW

**Comment by pobenliu** [comment]
@casey-collab  Please review this.

**Comment by casey-collab** [comment]
It looks like the files `Chinese/.DS_Store` and `.DS_Store` are empty.  Please make sure you don't add empty files to the repository.  You could add one sentence to each file, or delete the options that lead to them.

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by pobenliu** [comment]
@casey-collab  Please review this again. Thx

**Comment by casey-collab** [comment]
Looks great! :ferris_wheel:

**Pull request merged**
