### PR TITLE
Advice from mother

### PR DESCRIPTION
**Pull request by SusanRLindsay**
[Review on Reviewable](https://reviewable.io/reviews/udacity/create-your-own-adventure/1685)

### CODE REVIEW

**Comment by cbuckey-uda** [comment]
@casey-collab, please review this

**Comment by casey-collab** [comment]
Looks great! :wind_chime:

**Comment by casey-collab** [comment]
Unfortunately this pull request could not be automatically reviewed due to technical difficulty.

**Comment by cbuckey-uda** [comment]
@casey-collab, try again?

**Comment by casey-collab** [comment]
Looks great! :purple_heart:

**Pull request merged**
