### PR TITLE
Added to the bounce story some whacky stuff!

### PR DESCRIPTION
**Pull request by PanosGr94**

### CODE REVIEW

**Comment by PanosGr94** [comment]
@casey-collab Please review this for merging, thanks!

**Comment by casey-collab** [comment]
It looks like this pull request deletes quite a few lines. Was this a mistake?

**Comment by PanosGr94** [comment]
@casey-collab yes , those lines were not meant to be erased. I had troubles with my cloning.

**Comment by casey-collab** [comment]
It looks like this pull request deletes quite a few lines. Was this a mistake?

**Comment by PanosGr94** [comment]
@casey-collab yes

**Pull request closed without merging**
