### PR TITLE
Crackers

### PR DESCRIPTION
**Pull request by kchao-git**
Please review this, @casey-collab

### CODE REVIEW

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by kchao-git** [comment]
Not sure where the conflict is? Everything is saying it's up-to-date.

**Comment by cbuckey-uda** [comment]
Yeah, I don't see the conflict either. Sorry about that, I think it is a bug. @casey-collab, please look again.

**Comment by casey-collab** [comment]
Looks great! :purple_heart:

**Pull request merged**
