### PR TITLE
My contribution

### PR DESCRIPTION
**Pull request by sikegame**
@casey-collab

[Review on Reviewable](https://reviewable.io/reviews/udacity/create-your-own-adventure/2437)

### CODE REVIEW

**Comment by sikegame** [comment]
@casey-collab

**Comment by casey-collab** [comment]
Unfortunately this pull request could not be automatically reviewed due to technical difficulty.

**Comment by sikegame** [comment]
@casey-collab

**Comment by casey-collab** [comment]
Looks great! :seedling:

**Pull request merged**
