### PR TITLE
added a tiger to the story

### PR DESCRIPTION
**Pull request by apsommer**
Please review this, @casey-collab

### CODE REVIEW

**Comment by casey-collab** [comment]
Hey! Me! Review this @casey-collab

**Comment by casey-collab** [comment]
It looks like this pull request deletes quite a few lines. Was this a mistake?

**Comment by apsommer** [comment]
Hi @casey-collab ... no this was not a mistake. The README now includes more description in the first sentence and a link to the course website. The remaining portion of the README has not changed.

**Comment by casey-collab** [comment]
It looks like this pull request deletes quite a few lines. Was this a mistake?

**Comment by apsommer** [comment]
> 
> 
> It looks like this pull request deletes quite a few lines. Was this a mistake?

Hi @casey-collab ... no this was not a mistake. The README now includes more description in the first sentence and a link to the course website. The remaining portion of the README has not changed.

**Comment by casey-collab** [comment]
It looks like this pull request deletes quite a few lines. Was this a mistake?

**Comment by casey-collab** [comment]
It looks like this pull request deletes quite a few lines. Was this a mistake?

**Comment by 13rac1** [comment]
Huh... bot is looping :laughing: 

Can you put these changes in two separate PRs? I can review the README change.

**Comment by 13rac1** [comment]
I want Casey to merge the tiger story. I'll merge the README

**Comment by apsommer** [comment]
Sure, will separate the changes and submit as two pull requests now.

**Comment by apsommer** [comment]
Sure, separated the changes as two pull requests and submitted.

**Pull request closed without merging**
