### PR TITLE
Add history about go through door to stairs or factory

### PR DESCRIPTION
**Pull request by darkwizz**
Hello, I've create some story parts, so can you, @casey-collab review these.

### CODE REVIEW

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by darkwizz** [comment]
And now can you add my story, @casey-collab?

**Comment by casey-collab** [comment]
Looks great! :ribbon:

**Pull request merged**
