### PR TITLE
Scaring the green people at the marshmallow palace

### PR DESCRIPTION
**Pull request by deltaworld**
Added a new option to the investigation to scare the green people.
added option to investigate-marshmallow-structure.md with relative link
new dir scare-green
new scare-green.md

### CODE REVIEW

**Comment by cbuckey-uda** [comment]
@casey-collab, please review this

**Comment by casey-collab** [comment]
It looks like the file `english/explore-outside/investigate-marshmallow-structure/scare-green/scare-green.md` is empty.  Please make sure you don't add empty files to the repository.  You could add one sentence to this file, or delete the option that leads to it.

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by deltaworld** [comment]
The sentence in green-people.md has been added.

**Comment by cbuckey-uda** [comment]
@casey-collab, please take another look

**Comment by casey-collab** [comment]
Looks great! :purple_heart:

**Pull request merged**
