### PR TITLE
Fix first link in uva.md not working because GitHub doesn't understand relative reference-style links.

### PR DESCRIPTION
**Pull request by benjaminpwarren**
Please do this, if you can @casey-collab.

### CODE REVIEW

**Comment by casey-collab** [comment]
Unfortunately this pull request could not be automatically reviewed due to technical difficulty.

**Comment by cbuckey-uda** [comment]
Thanks for catching this @benjaminpwarren! Do you mind using a (non-relative) markdown link instead of html to be consistent with the rest of the repository? (Markdown links can be split up into multiple lines. Casey doesn't understand this, but I'll be happy to merge the pull request for you.)

**Comment by cbuckey-uda** [comment]
Well it's better this way than broken, so I'll go ahead and merge it. Thanks for the fix! :cake:

**Comment by benjaminpwarren** [comment]
Sorry, @cbuckey-uda, it was on my to-do list! Thank you.

Would you like me to do it the Markdown way and submit another pull request? 

p.s. thank you for the tip! I'd tried a few things and searched for how to do multi-line Markdown links but clearly my Google-fu wasn't working. I didn't think to break the line inside the parentheses!

**Pull request merged**
