### PR TITLE
journey down the trail of ters

### PR DESCRIPTION
**Pull request by makleks**

### CODE REVIEW

**Comment by makleks** [comment]
please merge this @casey-collab

**Comment by makleks** [comment]
please review @casey-collab

**Comment by pmallory** [comment]
@casey-collab can you review this PR please?

**Comment by casey-collab** [comment]
Looks great! :four_leaf_clover:

**Comment by casey-collab** [comment]
Unfortunately this pull request could not be automatically reviewed due to technical difficulty.

**Pull request merged**
