### PR TITLE
magic-words

### PR DESCRIPTION
**Pull request by ChrisCoates09**
You say the magic words that your evil sadistic uncle told you to say whenever you're in this situation. 

The marshmallow begins to get really hot. You look down and realize you're not standing on marshmallow anymore, but on molten lava. It becomes an active volcano, and you get burned to a crisp instantly. What were you doing listening to your evil sadistic uncle anyway?

### CODE REVIEW

**Comment by cbuckey-uda** [comment]
I'm confused because the description of this pull request seems like an addition to the story, but that addition is not included in the pull request. Was that intentional? I don't want to merge the change as-is, because it changes the events as described by a previous author (it removes the fact that your stomach quiets), which is not in the spirit of this repository. Build on what other people have already written, but don't remove it unless there are clear mistakes or spam.

**Comment by ChrisCoates09** [comment]
I'm trying to make an addition, but I don't know what I'm doing yet. Whole
lot of trial and error.

**Comment by cbuckey-uda** [comment]
Let me know if there's any way I can help!

**Comment by cbuckey-uda** [comment]
Closing this pull request due to lack of activity. If you ever have time to respond to the comments above, feel free to re-open it.

**Pull request closed without merging**
