### PR TITLE
Added path colours

### PR DESCRIPTION
**Pull request by Borris-the-Gnome**
@casey-collab

### CODE REVIEW

**Comment by Borris-the-Gnome** [comment]
@casey-collab

**Comment by casey-collab** [comment]
Hey! Me! Review this @casey-collab

If it cannot be merged just mention me and I'll check it again.

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by casey-collab** [comment]
Hey! Me! Review this @casey-collab

If it cannot be merged just mention me and I'll check it again.

**Comment by casey-collab** [comment]
Looks great! :seedling:

**Pull request merged**
