### PR TITLE
added a sentence to marshmallow.md story

### PR DESCRIPTION
**Pull request by gidenkvs**
Please review this, @casey-collab

### CODE REVIEW

**Comment by cbuckey-uda** [comment]
@casey-collab, you there?

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by gidenkvs** [comment]
Thank you for the reply.

I just saw your email. Once I get home I will get it done.

Thank you.

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by gidenkvs** [comment]
Did I not do that correctly?

If so, I do apologize, it is kinda mind bending.

Do you happen to know if there is a some kind of check-list that I can use
as I am leaning the push and pull commands.

I think I got the very basic of working in my one repositories, but I'm a
bit rusty when it comes to collaboration aspect.

Thank you very much.
V.g

**Comment by cbuckey-uda** [comment]
@gidenkvs, Since Casey is just a bot, she's easily confused. SHe will automatically review any pull request if you mention her username in a comment. Your previous comment mentioned her username because you replied to an email that contained it, and that email is included in your comment. (You can see it on the website by clicking the "..." on your comment.) Feel free to ignore those comments until you are ready to make the updates, and once you have done so you can mention her again for a review.

I'm not sure what kind of checklist you could use. What parts are you having trouble with? If you do find or create a resource that you like, please share it on the forums! I bet a lot of students would benefit from it.

**Comment by cbuckey-uda** [comment]
Closing this pull request due to lack of activity. If you ever have time to respond to the comments above, feel free to re-open it.

**Pull request closed without merging**
