### PR TITLE
german: continue 'schwimmen'

### PR DESCRIPTION
**Pull request by mujol**
Please review this, @casey-collab

### CODE REVIEW

**Comment by casey-collab** [comment]
It looks like the files `german/schwimmen/hunger/hunger.md` and `german/schwimmen/gefahr/gefahr.md` are empty.  Please make sure you don't add empty files to the repository.  You could add one sentence to each file, or delete the options that lead to them.

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by mujol** [comment]
Please review this, @casey-collab

**Comment by casey-collab** [comment]
Looks great! :heavy_check_mark:

**Pull request merged**
