### PR TITLE
Add line about dreaming and reality

### PR DESCRIPTION
**Pull request by mvescovo**
Please review this, @casey-collab

### CODE REVIEW

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by mvescovo** [comment]
Ok I pulled the latest upstream to my master, merged it with my changes branch, then pushed it to my remote changes branch and thus updated the pull request, @casey-collab

**Comment by casey-collab** [comment]
Looks great! :penguin:

**Pull request merged**
