### PR TITLE
Add modifed monkey

### PR DESCRIPTION
**Pull request by srxiaoj**
[Review on Reviewable](https://reviewable.io/reviews/udacity/create-your-own-adventure/2715)

### CODE REVIEW

**Comment by cbuckey-uda** [comment]
@casey-collab, please review this

**Comment by casey-collab** [comment]
Unfortunately this pull request could not be automatically reviewed due to technical difficulty.

**Comment by cbuckey-uda** [comment]
@srxiaoj, it looks like there is a huge number of changes in this pull request. Were they all intentional?

**Comment by srxiaoj** [comment]
I think i pull the repository first and then clone it again into my local
repository, that's why when i commit it, all the files have been changed

Best
Haorui

**Comment by cbuckey-uda** [comment]
@srxiaoj, I don't understand what you're saying. That shouldn't cause all the files to change.

**Comment by srxiaoj** [comment]
@cbuckey-uda Here is what I did, first, I create a folder on my laptop and initialized it as a git repository. Then I used git pull https://github.com/udacity/create-your-own-adventure.git to fetch all the data to my local repository. I then create a new branch called myStory. Then I realized that I'm supposed to use git clone, not git pull, so I did git clone https://github.com/udacity/create-your-own-adventure.git to clone the repository onto this myStroy branch. Finally, I changed one file content under /Chinese/manNamedMonkey and pull request. Hope this helps now.

Best
Haorui

**Comment by cbuckey-uda** [comment]
It looks like you cloned the "create-your-own-adventure" repository **inside** of itself. When you ran `git pull`, you created a folder called "your-folder-name", along with the files "your-folder-name/Chinese/大话西游.md" and all the other files in the original repository. Then when you ran `git clone`, you created "your-folder-name/create-your-own-adventure/Chinese/大话西游.md", again including all the other files in the original repository, but inside the new "create-your-own-adventure" subfolder.

The easiest way to fix it might be to start again; from outside your existing folder, try using git clone to clone the repository from scratch, and then try creating your branch and making your change again. (You can just copy the file from the existing folder into the new one.)

**Comment by cbuckey-uda** [comment]
Closing this pull request due to lack of activity. If you ever have time to respond to the comments above, feel free to re-open it.

**Pull request closed without merging**
