### PR TITLE
Altera alguns erros de direcionamento e adiciona 2 opções na história

### PR DESCRIPTION
**Pull request by GilBinga**
---

### CODE REVIEW

**Comment by GilBinga** [comment]
See this @casey-collab

**Comment by pmallory** [comment]
@casey-collab please review this PR

**Comment by casey-collab** [comment]
It looks like this pull request deletes quite a few lines. Was this a mistake?

**Comment by GilBinga** [comment]
I think there is no error.
I fixed some directory redirects.

**Comment by pmallory** [comment]
You are correct, you simply modified more files than Casey expects. Thanks for tidying things up :smiley: 

Muito obrigado!

**Comment by GilBinga** [comment]
Nope, thanks! =P

**Pull request merged**
