### PR TITLE
Fewer lines

### PR DESCRIPTION
**Pull request by jailorboy**
Please review this, @casey-collab

### CODE REVIEW

**Comment by jailorboy** [comment]
Please review this, @casey-collab

**Comment by casey-collab** [comment]
Unfortunately, pull requests adding more than 100 lines are not eligible for automatic merging.  If you wish to have this pull request auto-merged, please update it to add 100 lines or fewer.

**Comment by casey-collab** [comment]
Unfortunately, pull requests adding more than 100 lines are not eligible for automatic merging.  If you wish to have this pull request auto-merged, please update it to add 100 lines or fewer.

**Comment by cbuckey-uda** [comment]
See my comment on https://github.com/udacity/create-your-own-adventure/pull/1026 - I believe it may be the special files that are causing the problem.

**Comment by cbuckey-uda** [comment]
Closing this pull request due to lack of activity. If you ever have time to respond to the comments above, feel free to re-open it.

**Pull request closed without merging**
