### PR TITLE
Add programming adventure freecodecamp

### PR DESCRIPTION
**Pull request by mutwiri1**
@cassey-collab

### CODE REVIEW

**Comment by mutwiri1** [comment]
@casey-collab

**Comment by casey-collab** [comment]
Hey! Me! Review this @casey-collab

If it cannot be merged just mention me and I'll check it again.

**Comment by casey-collab** [comment]
Unfortunately this pull request could not be automatically reviewed due to technical difficulty.

**Comment by casey-collab** [comment]
Sorry, cannot merge this.

**Pull request closed without merging**
