### PR TITLE
add snow white story and its link

### PR DESCRIPTION
**Pull request by mzvast**
Please review this, @casey-collab

### CODE REVIEW

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by mzvast** [comment]
@casey-collab, I've merged upstream master into my branch,and I think this pull request will be fine now.

**Comment by casey-collab** [comment]
Looks great! :dart:

**Pull request merged**
