### PR TITLE
Update hands

### PR DESCRIPTION
**Pull request by rhart4004**
Please review this, @casey-collab

### CODE REVIEW

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by rhart4004** [comment]
Please review this, @casey-collab

**Comment by casey-collab** [comment]
Looks great! :rabbit:

**Pull request merged**
