### PR TITLE
Update bee-too story

### PR DESCRIPTION
**Pull request by mashaka**

### CODE REVIEW

**Comment by mashaka** [comment]
Please review this, @casey-collab

**Comment by casey-collab** [comment]
Looks great! :heavy_check_mark:

**Comment by casey-collab** [comment]
Unfortunately this pull request could not be automatically reviewed due to technical difficulty.

**Comment by cbuckey-uda** [comment]
@casey-collab, please try again

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Pull request closed without merging**
