### PR TITLE
Add a contribution on Portugues/Charity

### PR DESCRIPTION
**Pull request by mtyszler**

### CODE REVIEW

**Comment by mtyszler** [comment]
Please review this, @casey-collab

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by mtyszler** [comment]
I updated the request. There's no removal, only adding a blank line and new line.

It is safe to marge.

**Comment by mtyszler** [comment]
I merged locally with success! 

You can go ahead

**Comment by mtyszler** [comment]
Can you update me on the merge?

**Comment by mtyszler** [comment]
@casey-collab Can you update me on this merge?

**Pull request closed without merging**
