### PR TITLE
Added Oregon Trail

### PR DESCRIPTION
**Pull request by cvpeck**
@casey-collab @cbuckey-uda  Updated pull request. Now page reachable from the rest of the story. Thanks for the feedback.

### CODE REVIEW

**Comment by cbuckey-uda** [comment]
@casey-collab, please review this

**Comment by cbuckey-uda** [comment]
@casey-collab?

**Comment by cbuckey-uda** [comment]
@casey-collab?

**Comment by casey-collab** [comment]
Unfortunately this pull request could not be automatically reviewed due to technical difficulty.

**Comment by cbuckey-uda** [comment]
Hmmm, I don't know what's up with Casey. But it looks like your page is not reachable from the rest of the story. That is, if the reader starts at `language.md` and keeps clicking links, they will never reach this page. To fix this, you should find an existing page where you can add an option that leads to your page.

**Comment by cvpeck** [comment]
@casey-collab @cbuckey-uda Updated pull request. Now page reachable from the rest of the story. Thanks for the feedback.

**Comment by casey-collab** [comment]
Looks great! :smiley_cat:

**Pull request merged**
