### PR TITLE
Add EDM track to the list of chill music

### PR DESCRIPTION
**Pull request by shad-k**

### CODE REVIEW

**Comment by shad-k** [comment]
@casey-collab Have a look at this pull request, please.

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by shad-k** [comment]
@casey-collab Can you take another look at it now.

**Comment by casey-collab** [comment]
Looks great! :cherry_blossom:

**Pull request merged**
