### PR TITLE
Changed ending on call-scotty.md for 2nd time.

### PR DESCRIPTION
**Pull request by codeBarb**
@casey-collab updating the call scotty story line, but only have the 1 file changed now (not multiple ones like previously).

### CODE REVIEW

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by cbuckey-uda** [comment]
@casey-collab, please take another look.

**Comment by casey-collab** [comment]
Looks great! :thumbsup:

**Pull request merged**
