### PR TITLE
Add option 'traduire' to ecouter.md

### PR DESCRIPTION
**Pull request by Vanessaguillemain**
Please review this, @casey-collab. Thank you!

### CODE REVIEW

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by Vanessaguillemain** [comment]
Thank you for your review @casey-collab , I'm ready to merge ;)

**Comment by casey-collab** [comment]
Looks great! :cherry_blossom:

**Pull request merged**
