### PR TITLE
Greek story

### PR DESCRIPTION
**Pull request by naneziris**
Please review this, @casey-collab

### CODE REVIEW

**Comment by cbuckey-uda** [comment]
@casey-collab, you there?

**Comment by casey-collab** [comment]
Looks great! :shell:

**Comment by naneziris** [comment]
Thanks @cbuckey-uda & @casey-collab

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Can you resolve the merge conflicts locally and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by cbuckey-uda** [comment]
Haha, Casey thought you were asking her to merge your change again. But she's always happy to help, as am I!

**Comment by cbuckey-uda** [comment]
Yes, your pull request has been merged into the master branch of the repository, so everyone who visits should see your changes! And I'm glad you enjoyed the course!

**Pull request merged**
