### PR TITLE
add a line to the oh_daddy storyline

### PR DESCRIPTION
**Pull request by jakobjaderbo**
@casey-collab I hope the bot may still merge when the final line had to be edited with a newline to allow continuation of the story.

[Review on Reviewable](https://reviewable.io/reviews/udacity/create-your-own-adventure/2176)

### CODE REVIEW

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by jakobjaderbo** [comment]
@casey-collab alright, I think this should do it!

**Comment by casey-collab** [comment]
Looks great! :wind_chime:

**Pull request merged**
