### PR TITLE
My new time adventure

### PR DESCRIPTION
**Pull request by IreshMM**

### CODE REVIEW

**Comment by IreshMM** [comment]
Please review this, @casey-collab

**Comment by casey-collab** [comment]
I was broken now I'm back. Can I review this? @casey-collab

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by casey-collab** [comment]
I was broken now I'm back. Can I review this? @casey-collab

**Comment by casey-collab** [comment]
Looks great! :smiley_cat:

**Pull request merged**
