### PR TITLE
J'ajoute des plus mots

### PR DESCRIPTION
**Pull request by mtoback**
J'ai practiqué mon français parce que je y suis aller tôt

### CODE REVIEW

**Comment by mtoback** [comment]
Please review this, @casey-collab

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by mtoback** [comment]
Please review this, @casey-collab

I did pull from upstream master and I see no conflicts

**Comment by casey-collab** [comment]
Looks great! :night_with_stars:

**Pull request merged**
