### PR TITLE
Update 2spooky.md

### PR DESCRIPTION
**Pull request by Ohillio**
Adding comments to entice user to click choice 3

### CODE REVIEW

**Comment by Ohillio** [comment]
@casey-collab

**Comment by pmallory** [comment]
@casey-collab can you review this PR please?

**Comment by casey-collab** [comment]
Looks great! :lollipop:

**Comment by casey-collab** [comment]
Unfortunately this pull request could not be automatically reviewed due to technical difficulty.

**Comment by Ohillio** [comment]
Thanks guys !

**Pull request merged**
