### PR TITLE
Merge pull request #2 from udacity/master

### PR DESCRIPTION
**Pull request by justRishi**
Merge pull request #2318 from justRishi/master @casey-collab if don't want to go into the void , make yourself useful and merge this, por favor!

### CODE REVIEW

**Comment by casey-collab** [comment]
Looks great! :ice_cream:

**Comment by justRishi** [comment]
@casey-collab if don't want to go into the void , make yourself useful and merge this, por favor!

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by justRishi** [comment]
@casey-collab if don't want to go into the void , make yourself useful and merge this, por favor!

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by justRishi** [comment]
Please review this, @casey-collab

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Pull request merged**
