### PR TITLE
Story Continues

### PR DESCRIPTION
**Pull request by gammaguy**

### CODE REVIEW

**Comment by cbuckey-uda** [comment]
@casey-collab, please review this

**Comment by casey-collab** [comment]
Unfortunately this pull request could not be automatically reviewed due to technical difficulty.

**Comment by cbuckey-uda** [comment]
I'm happy to add your change with Luke and Yoda, but this commit also removes the option to step through the door. Could you add that back?

**Comment by cbuckey-uda** [comment]
Closing this pull request due to lack of activity. If you ever have time to respond to the comment above, feel free to re-open it.

**Pull request closed without merging**
