### PR TITLE
added my part of google to the story

### PR DESCRIPTION
**Pull request by punithg**
@casey-collab check out my change please.

[Review on Reviewable](https://reviewable.io/reviews/udacity/create-your-own-adventure/1844)

### CODE REVIEW

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by punithg** [comment]
@casey-collab there are no conflicts..check out now

**Comment by casey-collab** [comment]
Unfortunately, this pull request conflicts with another change. Could you merge the master branch of the original repository into your branch, resolve the merge conflicts, and update the pull request?

**Comment by casey-collab** [comment]
Besides my other comments, this looks good!  Once you respond to those, this should be good to merge.

**Comment by cbuckey-uda** [comment]
@punithg it looks to me like there are merge conflicts. Do you see how right above the comment box, it says "We can't automatically merge this pull request", with a gray icon instead of a green? That means the pull request cannot be merged due to merge conflicts. Like Casey said, this means you will need to merge the master branch of the original repository into your branch. When you do, there should be merge conflicts, which you will need to resolve. Then you should push your merge commit to update the pull request.

**Comment by punithg** [comment]
@cbuckey-uda thank you very much.i got that working...and i love this course

**Comment by cbuckey-uda** [comment]
Great, I'm glad you enjoyed the course! And the pull request looks good to go.

**Pull request merged**
